default_language_version:
  python: python3.9
minimum_pre_commit_version: 2.3.0
repos:
- hooks:
  - exclude: ^docs/.*$
    id: black
    name: Format code (black)
  repo: https://github.com/psf/black
  rev: 21.12b0
- hooks:
  - additional_dependencies:
    - black==20.8b1
    args:
    - -l
    - '79'
    id: blacken-docs
    language_version: python3
    name: Format docs (blacken-docs)
  repo: https://github.com/asottile/blacken-docs
  rev: v1.12.0
- hooks:
  - additional_dependencies:
    - toml
    id: isort
  repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
- hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: check-merge-conflict
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
- hooks:
  - additional_dependencies: &id001
    - flake8-broken-line==0.2.0
    - flake8-bugbear==20.1.4
    - flake8-builtins==1.5.2
    - flake8-comprehensions==3.2.2
    - flake8-eradicate==0.3.0
    - flake8-mutable==1.2.0
    - flake8-pie==0.5.0
    - flake8-quotes==3.0.0
    - flake8-string-format==0.3.0
    - flake8-tidy-imports==4.1.0
    - pep8-naming==0.10.0
    exclude: ^docs/.*$
    id: flake8
    name: Lint code (flake8)
  repo: https://gitlab.com/PyCQA/flake8
  rev: 3.9.2
- hooks:
  - additional_dependencies: *id001
    exclude: ^docs/.*$
    id: yesqa
    name: Lint code (yesqa)
  repo: https://github.com/asottile/yesqa
  rev: v1.3.0
